name: gig_hub
description: "this is gighub"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_rating_stars: ^1.1.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.0
  shimmer: ^3.0.0
  http: ^1.4.0
  flutter_dotenv: ^5.2.0
  flutter_typeahead: ^5.2.0
  audio_waveforms: ^1.3.0
  just_audio: ^0.10.4
  path_provider: ^2.0.0
  flutter_image_slideshow: ^0.1.6
  pinch_zoom: ^2.0.1
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  app_links: ^6.4.0
  liquid_glass_renderer: ^0.1.1-dev.9
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  google_sign_in: ^7.1.1
  flutter_facebook_auth: ^7.1.2
  cloud_firestore: ^5.6.11
  hive_flutter: ^1.1.0
  flutter_appauth: ^6.0.6
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  provider: ^6.1.5
  firebase_storage: ^12.4.9
  intl: ^0.20.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/gighub_logo.png
    - assets/images/default_avatar.jpg
    - assets/icons/
    - .env
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_background: '#000000'

flutter_native_splash:
  background_image: "assets/images/blackscreen_splash.png"
  image: "assets/images/splash_logo.png"
  android: true
  ios: true
  android_12:
    image: "assets/images/splash_logo.png"
    icon_background_color: '#000000'
    color: '#000000'